[database]
path = "themis.db"

[auth]
cookie_name = "themis_auth"
cookie_key = "your-secret-signature-key-change-in-production-min-32-chars"
cookie_expiry_days = 30

[gemini]
api_key = "AIzaSyCHsfs1P-jMtZ7UtlKJwivl0gX1EIWcT84"

[app]
admin_email = "admin@themis.app"
admin_password = "admin123"
app_name = "Themis"
